name: Codespell Check

on: [push, pull_request]

permissions:
  contents: read

jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run Codespell
      uses: codespell-project/actions-codespell@v2
      with:
        check_hidden: true
        
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Codespell output as artifact
      uses: actions/upload-artifact@v3
      with:
        name: codespell-output
        path: codespell_output.md
